package com.example.util

object OnboardingStrings {

    enum class AppLanguage {
        ENGLISH, HINDI, URDU
    }

    class LanguageContent(
        val appTitle: String,
        val subtitle: String,
        val continueText: String,
        val consentScreenTitle: String,
        val consentSubtitle: String,
        val dataCollectionConsentLabel: String,
        val parentConsentLabel: String,
        val parentNameLabel: String,
        val parentHelperText: String,
        val minorNoticeText: String,
        val consentMainNoticeBlock: String,
        val profileDetailsTitle: String,
        val firstNameLabel: String,
        val lastNameLabel: String,
        val genderLabel: String,
        val maleLabel: String,
        val femaleLabel: String,
        val otherLabel: String,
        val dobLabel: String,
        val bloodGroupLabel: String,
        val activeDonorLabel: String,
        val activeDonorHelper: String,
        val cityNameLabel: String,
        val stateNameLabel: String,
        val idVerificationTitle: String,
        val idVerificationSubtitle: String,
        val aadhaarInputLabel: String,
        val aadhaarErrorStarts01: String,
        val aadhaarErrorLength: String,
        val aadhaarErrorChecksum: String,
        val aadhaarValidLabel: String,
        val samagraLabel: String,
        val optionalLabel: String,
        val idMaskingExplanation: String,
        val privacyFaqTitle: String,
        val privacyFaqBody: String,
        val finishOnboardingBtn: String,
        val previousBtn: String,
        val activeProfileDashboardTitle: String,
        val welcomeBackTitle: String,
        val yourMaskedGovId: String,
        val yourGovIdSecureHash: String,
        val statusVerifiedLabel: String,
        val statusActiveLabel: String,
        val statusInactiveLabel: String,
        val statusConsentRevoked: String,
        val profileDetailsTab: String,
        val settingsTab: String,
        val deleteWarningTitle: String,
        val deleteWarningBody: String,
        val revokeBtnLabel: String,
        val registerNewProfileBtn: String,
        val consentWithdrawnNotice: String,
        val under18Notice: String,
        val fieldRequiredError: String
    )

    private val englishContent = LanguageContent(
        appTitle = "Nilgar Community Platform",
        subtitle = "Empowering our community with secure genealogy, localized utility, and offline emergency support.",
        continueText = "Get Started",
        consentScreenTitle = "DPDP Act 2023 Consent Notice",
        consentSubtitle = "Under Section 6 of India's Digital Personal Data Protection Act, we require your explicit, free, and informed consent to process your profile.",
        dataCollectionConsentLabel = "I explicitly consent to the collection, secure storage, and processing of my personal details for community services.",
        parentConsentLabel = "I, as parent / legal guardian, hereby verify and provide consent for the minor named above.",
        parentNameLabel = "Parent / Legal Guardian Full Name",
        parentHelperText = "Required for minors under 18 years of age.",
        minorNoticeText = "Note: Users under 18 require parental or legal guardian consent and verification to proceed.",
        consentMainNoticeBlock = "To provide you with secure community genealogy tracking, geofenced emergency blood-donor matching, and localized community services, the Nilgar Community Platform collects:\n\n" +
                "• Your Identity: First Name, Last Name, Gender, and Birth Date.\n" +
                "• Localisation: City name and State name.\n" +
                "• Emergency Healthcare: Blood Group and active donor availability.\n" +
                "• Secure Validator (Non-Retrievable Hash): Masked Government ID (XXXX-XXXX-last4) and SHA-256 secure hash to prevent duplicate registrations.\n\n" +
                "Your information is stored securely in an offline-first encrypted database. You have the right to withdraw your consent at any time from the app Settings, which will immediately restrict your visibility and flag your data for deletion.",
        profileDetailsTitle = "Profile Particulars",
        firstNameLabel = "First Name",
        lastNameLabel = "Last Name",
        genderLabel = "Gender",
        maleLabel = "Male",
        femaleLabel = "Female",
        otherLabel = "Other",
        dobLabel = "Date of Birth (YYYY-MM-DD)",
        bloodGroupLabel = "Blood Group",
        activeDonorLabel = "Register as Active Blood Donor",
        activeDonorHelper = "When active, nearby community members can contact you for emergency blood matching in life-saving situations.",
        cityNameLabel = "City",
        stateNameLabel = "State",
        idVerificationTitle = "Identity Verification",
        idVerificationSubtitle = "To maintain directory integrity, we inspect your Aadhaar. To respect UIDAI mandates, the raw number is never stored or transmitted.",
        aadhaarInputLabel = "Aadhaar Number (12 Digits)",
        aadhaarErrorStarts01 = "Invalid: Aadhaar numbers can never start with '0' or '1'.",
        aadhaarErrorLength = "Invalid: Aadhaar must be exactly 12 numeric digits.",
        aadhaarErrorChecksum = "Verification Failed: Checksum checksum error detected. Please check for typos.",
        aadhaarValidLabel = "Aadhaar checksum fully verified locally!",
        samagraLabel = "Samagra Member ID (9 Digits)",
        optionalLabel = "Optional",
        idMaskingExplanation = "Under strict UIDAI data guidelines, we mask the ID to the last 4 digits (e.g. XXXX-XXXX-9815) and generate a local cryptographically secure SHA-256 hash combined with a static salt. The original 12 digits are discarded from memory instantly.",
        privacyFaqTitle = "Privacy Guarantee",
        privacyFaqBody = "The Nilgar Community Initiative operates on a strictly zero-infrastructure-cost blueprint. No data is harvested, analyzed, or shared with third-party networks. All communications employ secure end-to-end HTTPS synchronization.",
        finishOnboardingBtn = "Complete Registration",
        previousBtn = "Back",
        activeProfileDashboardTitle = "Community Hub",
        welcomeBackTitle = "Welcome to your Profile,",
        yourMaskedGovId = "Masked Gov ID",
        yourGovIdSecureHash = "Deduplication Secure Hash (SHA-256)",
        statusVerifiedLabel = "Status: Verified",
        statusActiveLabel = "Active Member",
        statusInactiveLabel = "Deactivated (Consent Revoked)",
        statusConsentRevoked = "Data restricted. Pending deletion queue sweep.",
        profileDetailsTab = "Identity Profile",
        settingsTab = "DPDP Compliance & Settings",
        deleteWarningTitle = "Withdraw Consent?",
        deleteWarningBody = "Warning: Withdrawing consent under DPDP Act 2023 will immediately mask your record, remove you from active directory lookup and emergency donor lists, and queue your profile for permanent deletion on the next synchronization sweep. This action is irreversible.",
        revokeBtnLabel = "Withdraw Consent & Delete Data",
        registerNewProfileBtn = "Start New Registration",
        consentWithdrawnNotice = "You have successfully withdrawn your DPDP consent. Your data has been restricted and queued for permanent deletion.",
        under18Notice = "Minor: Consent verified by parent/guardian",
        fieldRequiredError = "This field is required"
    )

    private val hindiContent = LanguageContent(
        appTitle = "निलगर कम्युनिटी प्लेटफार्म",
        subtitle = "सुरक्षित वंशावली, स्थानीय उपयोगिता और आपातकालीन सहायता के साथ हमारे समुदाय को सशक्त बनाना।",
        continueText = "शुरू करें",
        consentScreenTitle = "DPDP अधिनियम 2023 सहमति सूचना",
        consentSubtitle = "भारत के डिजिटल व्यक्तिगत डेटा संरक्षण (DPDP) अधिनियम की धारा 6 के तहत, आपकी सहमति स्वैच्छिक, विशिष्ट, और सुविज्ञ होनी आवश्यक है।",
        dataCollectionConsentLabel = "मैं समुदाय सेवाओं के लिए अपनी व्यक्तिगत जानकारी के संग्रह, सुरक्षित भंडारण और प्रसंस्करण के लिए स्पष्ट रूप से सहमति देता/देती हूँ।",
        parentConsentLabel = "मैं, माता-पिता / कानूनी अभिभावक के रूप में, नाबालिग के लिए डेटा संग्रह की पुष्टि और सहमति प्रदान करता हूँ।",
        parentNameLabel = "माता-पिता / कानूनी अभिभावक का पूरा नाम",
        parentHelperText = "18 वर्ष से कम उम्र के नाबालिगों के लिए आवश्यक है।",
        minorNoticeText = "नोट: 18 वर्ष से कम उम्र के उपयोगकर्ताओं को आगे बढ़ने के लिए माता-पिता या कानूनी अभिभावक की सहमति और सत्यापन की आवश्यकता होती है।",
        consentMainNoticeBlock = "सुरक्षित वंशावली ट्रैकिंग, आपातकालीन रक्तदाता मिलान और स्थानीय सेवाएं प्रदान करने के लिए, निलगर कम्युनिटी निम्न एकत्रित करती है:\n\n" +
                "• आपकी पहचान: प्रथम नाम, अंतिम नाम, लिंग और जन्म तिथि।\n" +
                "• स्थानीयकरण: शहर और राज्य का नाम।\n" +
                "• आपातकालीन स्वास्थ्य: रक्त समूह और सक्रिय रक्तदाता उपलब्धता।\n" +
                "• सुरक्षित सत्यापन (अपुनर्प्राप्त करने योग्य हैश): डुप्लिकेट प्रविष्टियों को रोकने के लिए मास्क की गई सरकारी आईडी (XXXX-XXXX-last4) और SHA-256 सुरक्षित हैश।\n\n" +
                "आपकी जानकारी एक सुरक्षित, स्थानीय एन्क्रिप्टेड डेटाबेस में संग्रहित की जाती है। आपके पास सेटिंग्स से किसी भी समय अपनी सहमति वापस लेने का अधिकार है, जिससे आपकी दृश्यता तुरंत प्रतिबंधित हो जाएगी और आपका डेटा हटा दिया जाएगा।",
        profileDetailsTitle = "व्यक्तिगत विवरण",
        firstNameLabel = "प्रथम नाम",
        lastNameLabel = "अंतिम नाम",
        genderLabel = "लिंग",
        maleLabel = "पुरुष",
        femaleLabel = "महिला",
        otherLabel = "अन्य",
        dobLabel = "जन्म तिथि (YYYY-MM-DD)",
        bloodGroupLabel = "रक्त समूह",
        activeDonorLabel = "सक्रिय रक्तदाता के रूप में पंजीकरण करें",
        activeDonorHelper = "सक्रिय होने पर, नजदीकी समुदाय के सदस्य आपातकालीन स्थिति में जीवन रक्षक रक्त मिलान के लिए आपसे संपर्क कर सकते हैं।",
        cityNameLabel = "शहर",
        stateNameLabel = "राज्य",
        idVerificationTitle = "पहचान सत्यापन",
        idVerificationSubtitle = "डायरेक्टरी की सत्यता बनाए रखने के लिए हम आपकी आधार संख्या की जांच करते हैं। नियमों के तहत, मूल संख्या को कभी संग्रहित या प्रेषित नहीं किया जाता है।",
        aadhaarInputLabel = "आधार संख्या (12 अंक)",
        aadhaarErrorStarts01 = "अमान्य: आधार संख्या कभी भी '0' या '1' से शुरू नहीं हो सकती।",
        aadhaarErrorLength = "अमान्य: आधार में ठीक 12 अंक होने चाहिए।",
        aadhaarErrorChecksum = "सत्यापन विफल: अंकों में त्रुटि पाई गई। कृपया पुनः जांचें।",
        aadhaarValidLabel = "आधार संख्या का स्थानीय स्तर पर सफलतापूर्वक सत्यापन किया गया!",
        samagraLabel = "समग्र सदस्य आईडी (9 अंक)",
        optionalLabel = "वैकल्पिक",
        idMaskingExplanation = "सख्त डेटा नियमों के तहत, हम आईडी को अंतिम 4 अंकों (जैसे XXXX-XXXX-9815) में बदल देते हैं और एक सुरक्षित SHA-256 हैश उत्पन्न करते हैं। मूल 12 अंक तुरंत हटा दिए जाते हैं।",
        privacyFaqTitle = "गोपनीयता की गारंटी",
        privacyFaqBody = "यह ऐप पूरी तरह से सुरक्षित है। कोई भी डेटा तीसरे पक्ष के नेटवर्क के साथ साझा नहीं किया जाता है। सभी संचार सुरक्षित एंड-टू-एंड HTTPS पर सिंक होते हैं।",
        finishOnboardingBtn = "पंजीकरण पूर्ण करें",
        previousBtn = "पीछे",
        activeProfileDashboardTitle = "कम्युनिटी हब",
        welcomeBackTitle = "अपनी प्रोफाइल में आपका स्वागत है,",
        yourMaskedGovId = "मास्क की गई सरकारी आईडी",
        yourGovIdSecureHash = "सुरक्षित हैश (SHA-256)",
        statusVerifiedLabel = "स्थिति: सत्यापित",
        statusActiveLabel = "सक्रिय सदस्य",
        statusInactiveLabel = "सहमति वापस ली गई",
        statusConsentRevoked = "डेटा प्रतिबंधित है और हटाने की सूची में है।",
        profileDetailsTab = "पहचान प्रोफ़ाइल",
        settingsTab = "सहमतियां और सेटिंग्स",
        deleteWarningTitle = "सहमति वापस लें?",
        deleteWarningBody = "चेतावनी: सहमति वापस लेने से आपकी प्रोफ़ाइल तुरंत निष्क्रिय हो जाएगी, समुदाय डायरेक्टरी से आपका नाम हट जाएगा, और डेटा स्थायी रूप से मिटा दिया जाएगा। यह क्रिया अपरिवर्तनीय है।",
        revokeBtnLabel = "सहमति वापस लें और डेटा हटाएं",
        registerNewProfileBtn = "नया पंजीकरण शुरू करें",
        consentWithdrawnNotice = "आपने सफलतापूर्वक अपनी सहमति वापस ले ली है। आपका डेटा हटा दिया जाएगा।",
        under18Notice = "नाबालिग: अभिभावक द्वारा सहमत",
        fieldRequiredError = "यह फ़ील्ड आवश्यक है"
    )

    private val urduContent = LanguageContent(
        appTitle = "نیلگر کمیونٹی پلیٹ فارم",
        subtitle = "محفوظ شجرہ نسب، مقامی افادیت اور ہنگامی امداد کے ساتھ اپنے تفصیلی خاندان کو بااختیار بنانا۔",
        continueText = "شروع کریں",
        consentScreenTitle = "ڈی پی ڈی پی ایکٹ 2023 رضامندی نوٹس",
        consentSubtitle = "انڈیا کے ڈیجیٹل پرسنل ڈیٹا پروٹیکشن (DPDP) ایکٹ کے تحت، آپ کی رضامندی واضح اور باخبر ہونی چاہیے۔",
        dataCollectionConsentLabel = "میں کمیونٹی سروسز کے لیے اپنے ذاتی ڈیٹا کے جمع، محفوظ اور پروسیس کرنے کی واضح طور پر رضامندی دیتا/دیتی ہوں۔",
        parentConsentLabel = "میں بمطابق والد/والدہ/سرپرست اس نابالغ کے ڈیٹا پروسیس کی تصدیق اور رضامندی فراہم کرتا ہوں۔",
        parentNameLabel = "والد/والدہ یا قانونی سرپرست کا پورا نام",
        parentHelperText = "18 سال سے کم عمر نابالغوں کے لیے لازمی ہے۔",
        minorNoticeText = "نوٹ: 18 سال سے کم عمر صارفین کو آگے بڑھنے کے لیے والدین یا قانونی سرپرست کی تصدیق کی ضرورت ہوتی ہے۔",
        consentMainNoticeBlock = "شجرہ نسب، ہنگامی خون کے عطیہ دہندگان کا ملاپ، اور مقامی کمیونٹی کی خدمات فراہم کرنے کے لیے، نیلگر کمیونٹی حاصل کرتی ہے:\n\n" +
                "• آپ کی شناختی معلومات: پہلا نام، آخری نام، جنس اور تاریخ پیدائش۔\n" +
                "• مقام: شہر اور ریاست کا نام۔\n" +
                "• ہنگامی صحت: خون کا گروپ اور عطیہ دہندہ رضامندی۔\n" +
                "• محفوظ تصدیق (ناقابل واپسی ہیش): رجسٹریشن کے دہراؤ کو روکنے کے لیے ماسک شدہ شناختی کارڈ (XXXX-XXXX-last4) اور SHA-256 محفوظ ہیش۔\n\n" +
                "آپ کا ڈیٹا محفوظ انکرپٹڈ ڈیٹا بیس میں رکھا جاتا ہے۔ آپ کسی بھی وقت سیٹنگز کے ذریعے اپنی رضامندی واپس لے سکتے ہیں، جس سے آپ کا پروفائل فوری طور پر بلاک اور ڈیٹا حذف کر دیا جائے گا۔",
        profileDetailsTitle = "پروفائل کی تفصیلات",
        firstNameLabel = "پہلا نام",
        lastNameLabel = "آخری نام",
        genderLabel = "جنس",
        maleLabel = "مرد",
        femaleLabel = "عورت",
        otherLabel = "دیگر",
        dobLabel = "تاریخ پیدائش (YYYY-MM-DD)",
        bloodGroupLabel = "خون کا گروپ",
        activeDonorLabel = "بطور ہنگامی خون کا عطیہ دہندہ رجیسٹر کریں",
        activeDonorHelper = "جب فعال ہو، قریبی کمیونٹی ممبرز ہنگامی صورتحال میں بچاؤ کے لیے آپ سے رابطہ کر سکتے ہیں۔",
        cityNameLabel = "شہر",
        stateNameLabel = "ریاست",
        idVerificationTitle = "شناخت کی تصدیق",
        idVerificationSubtitle = "ڈائریکٹری کے تقدس کو قائم رکھنے کے لیے ہم آپ کے آدھار کارڈ کی تصدیق کرتے ہیں۔ قواعد کے مطابق اصل نمبر کبھی محفوظ یا بھیجا نہیں جاتا۔",
        aadhaarInputLabel = "آدھار نمبر (12 ہندسے)",
        aadhaarErrorStarts01 = "غیر موزوں: آدھار نمبر کبھی بھی '0' یا '1' سے شروع نہیں ہو سکتا۔",
        aadhaarErrorLength = "غیر موزوں: آدھار میں ٹھیک 12 ہندسے ہونے چاہئیں۔",
        aadhaarErrorChecksum = "تصدیق ناکام: ہندسوں میں غلطی پائی گئی ہے۔ براہ کرم دوبارہ چیک کریں۔",
        aadhaarValidLabel = "آدھار نمبر کی لوکل تصدیق کامیاب رہی!",
        samagraLabel = "سمگر ممبر آئی ڈی (9 ہندسے)",
        optionalLabel = "اختیاری",
        idMaskingExplanation = "سخت ضوابط کے تحت، ہم آئی ڈی کے صرف آخری 4 ہندسے (جیسے XXXX-XXXX-9815) محفوظ کرتے ہیں اور ایک محفوظ ہیش بناتے ہیں۔ اصل نمبر فوراً میموری سے غائب کر دیا جاتا ہے۔",
        privacyFaqTitle = "رازداری کی ضمانت",
        privacyFaqBody = "یہ ایپلیکیشن مکمل طور پر محفوظ ہے۔ کوئی بھی ڈیٹا کسی تیسرے فریق کو فراہم نہیں کیا جاتا۔ تمام معلومات نجی اور انکرپٹڈ رہتی ہیں۔",
        finishOnboardingBtn = "رجسٹریشن مکمل کریں",
        previousBtn = "واپس",
        activeProfileDashboardTitle = "کمیونٹی ہب",
        welcomeBackTitle = "اپنے پروفائل میں خوش آمدید،",
        yourMaskedGovId = "ماسک شدہ شناختی کارڈ",
        yourGovIdSecureHash = "محفوظ ہیش (SHA-256)",
        statusVerifiedLabel = "حیثیت: تصدیق شدہ",
        statusActiveLabel = "فعال رکن",
        statusInactiveLabel = "رضامندی واپس لی گئی",
        statusConsentRevoked = "ڈیٹا محدود کر دیا گیا ہے اور حذف کرنے کی قطار میں ہے۔",
        profileDetailsTab = "شناختی پروفائل",
        settingsTab = "رضامندی اور ترتیبات",
        deleteWarningTitle = "رضامندی واپس لیں؟",
        deleteWarningBody = "انتباہ: رضامندی واپس لینے سے آپ کا اکاؤنٹ فوری طور پر غیر فعال ہو جائے گا، آپ کا نام ہٹ جائے گا، اور ڈیٹا مستقل طور پر مٹ جائے گا۔ یہ عمل ناقابل واپسی ہے۔",
        revokeBtnLabel = "رضامندی واپس لیں اور اکاؤنٹ ڈیلیٹ کریں",
        registerNewProfileBtn = "نیا اکاؤنٹ رجسٹر کریں",
        consentWithdrawnNotice = "آپ نے کامیابی کے ساتھ رضامندی واپس لے لی ہے۔ آپ کی تفصیلات حذف کر دی جائیں گی۔",
        under18Notice = "نابالغ: سرپرست کی رضامندی تصدیق شدہ",
        fieldRequiredError = "یہ فیلڈ درکار ہے"
    )

    fun getContent(lang: AppLanguage): LanguageContent {
        return when (lang) {
            AppLanguage.ENGLISH -> englishContent
            AppLanguage.HINDI -> hindiContent
            AppLanguage.URDU -> urduContent
        }
    }
}
